---
language: python
python: "2.7"

before_install:
    - sudo apt-get update -qq
    - docker pull centos/systemd:latest

install:
    - git clone https://github.com/ansible/ansible-container.git
    - cd ansible-container
    - pip install -e .[docker]
    #    - pip install ansible ansible-container[docker]

services:
    - docker

script:
    - ansible-container build

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
       docker login -u "$DOCKERHUB_NAME" -p="$DOCKERHUB_PASS";
       docker images;
       docker tag docker-sshd-docker-sshd:latest cmsj/docker-sshd:latest;
       docker push cmsj/docker-sshd:latest;
      fi
